version: '3'
services:
   mydbapp:
      build: ./web
      ports:
        - "8888:8080"
      depends_on:
        - db

   db:
      image: postgres:9.5
      ports:
        - "5432:5432"
      volumes:
        - db_data:/var/lib/postgresql/data
      container_name: db
volumes:
   db_data:

